"""ForenKey and relationship

Revision ID: f24ae819272c
Revises: 
Create Date: 2022-05-11 17:53:37.879943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f24ae819272c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('categoria_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'produto', 'categoria', ['categoria_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'produto', type_='foreignkey')
    op.drop_column('produto', 'categoria_id')
    # ### end Alembic commands ###
